FROM salsadigital/wordpress-lagoon-cli:latest as builder

FROM uselagoon/nginx

COPY .docker/nginx/nginx.conf /etc/nginx/conf.d/app.conf

# Adding Stagefile helper
COPY .docker/nginx/stagefile-*.conf /etc/nginx/conf.d/wordpress/

RUN fix-permissions /etc/nginx/conf.d && \
    fix-permissions /etc/nginx/conf.d/wordpress

# Create temporary wordpress log file.
RUN touch /tmp/wp-errors.log && fix-permissions /tmp/wp-errors.log

COPY --from=builder /app /app

ENV WEBROOT=web
