ARG PHP_VERSION=8.3
# When updatating image tag, it breaks wp-cli database commands.
# Keep at 25.2.0 until https://github.com/salsadigitalauorg/wordpress-lagoon/issues/15
# is resolved.
FROM uselagoon/php-${PHP_VERSION}-cli:25.2.0

RUN apk update \
    && apk add --no-cache \
    php-exif \
    php-mbstring \
    tzdata

COPY composer.* wp.json project.json /app/
COPY .docker/wordpress/wp-config.php /app/.docker/wordpress/wp-config.php

RUN /bin/rm -Rf /app/web/wp && mkdir -p /app/web/wp
RUN composer self-update && \
    composer clearcache && \
    composer install --no-dev -n --prefer-dist --working-dir=/app

# Install wp-cli
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp && chmod +x /usr/local/bin/wp

# Add function to .bashrc to run wp-cli with --allow-root and --path=/app/web/wp.
RUN echo 'wp() { /usr/local/bin/wp "$@" --allow-root --path=/app/web/wp; }' >>  ~/.bashrc

COPY web /app/web

COPY themes /app/web/content/themes/
COPY plugins /app/web/content/plugins/

# Remove themes shipped with wordpress in the web/wp/wp-content/themes.
    RUN /bin/rm -Rf /app/web/wp/wp-content/themes /app/web/wp/wp-config-sample.php

# Adding caching directory.
RUN mkdir -p /app/web/content/cache && \
    fix-permissions /app/web/content/cache

# Create temporary wordpress log file.
RUN touch /tmp/wp-errors.log && fix-permissions /tmp/wp-errors.log

# Created database backups directory.
RUN mkdir -p /app/web/content/uploads/backups && \
    fix-permissions /app/web/content/uploads

ENV WEBROOT=web
ENV PAGER=less
